// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezdadquvbpebihirximz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6ZGFkcXV2YnBlYmloaXJ4aW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzIzOTYsImV4cCI6MjA2Mzg0ODM5Nn0.49muZyXv6XboviBiKCK2d_kJIhs5smrRASxDVDbAlVs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);